package restaurantpos;

import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.PrintWriter;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.border.*;

/**
 * AdminDashboard - Admin panel for managing menu items and viewing buyer history
 *
 * @author JollibeePOS
 */
public class AdminDashboard extends javax.swing.JDialog {

    // Jollibee Brand Colors
    private static final Color JOLLIBEE_RED = new Color(204, 0, 0);
    private static final Color JOLLIBEE_YELLOW = new Color(255, 204, 0);
    private static final Color JOLLIBEE_DARK_RED = new Color(153, 0, 0);
    private static final Color JOLLIBEE_LIGHT_YELLOW = new Color(255, 238, 153);

    private DatabaseHandler dbHandler;
    private List<MenuItem> menuItems;
    private List<BuyerHistory> buyerHistory;
    private MenuItem selectedMenuItem;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        dbHandler = DatabaseHandler.getInstance();
        initComponents();
        // Ensure tabs work properly
        tabbedPane.setEnabled(true);
        tabbedPane.setFocusable(true);
        tabbedPane.setRequestFocusEnabled(true);
        // Set explicit size to ensure tabs are visible
        setSize(1100, 700);
        loadLogo();
        loadMenuItems();
        loadBuyerHistory();
        updateDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        closePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        statsPanel = new javax.swing.JPanel();
        totalSalesPanel = new javax.swing.JPanel();
        totalSalesLabel = new javax.swing.JLabel();
        totalSalesValue = new javax.swing.JLabel();
        totalOrdersPanel = new javax.swing.JPanel();
        totalOrdersLabel = new javax.swing.JLabel();
        totalOrdersValue = new javax.swing.JLabel();
        menuItemsCountPanel = new javax.swing.JPanel();
        menuItemsCountLabel = new javax.swing.JLabel();
        menuItemsCountValue = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        menuTab = new javax.swing.JPanel();
        menuScrollPane = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        menuButtonPanel = new javax.swing.JPanel();
        addMenuItemButton = new javax.swing.JButton();
        editMenuItemButton = new javax.swing.JButton();
        deleteMenuItemButton = new javax.swing.JButton();
        refreshMenuButton = new javax.swing.JButton();
        historyTab = new javax.swing.JPanel();
        historyTopPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        showAllButton = new javax.swing.JButton();
        historyScrollPane = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        historyButtonPanel = new javax.swing.JPanel();
        refreshHistoryButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jollibee Admin Dashboard");
        setModal(true);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(204, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(980, 70));
        headerPanel.setLayout(new java.awt.BorderLayout());

        logoPanel.setBackground(new java.awt.Color(204, 0, 0));
        logoPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        logoLabel.setPreferredSize(new java.awt.Dimension(70, 70));
        logoPanel.add(logoLabel);

        titleLabel.setFont(new java.awt.Font("Arial", 1, 24));
        titleLabel.setForeground(new java.awt.Color(255, 204, 0));
        titleLabel.setText("JOLLIBEE ADMIN DASHBOARD");
        logoPanel.add(titleLabel);

        headerPanel.add(logoPanel, java.awt.BorderLayout.WEST);

        closePanel.setBackground(new java.awt.Color(204, 0, 0));
        closePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setFont(new java.awt.Font("Arial", 1, 14));
        closeButton.setText("Close");
        closeButton.setBackground(new java.awt.Color(255, 204, 0));
        closeButton.setForeground(new java.awt.Color(153, 0, 0));
        closeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        closeButton.setFocusPainted(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        closePanel.add(closeButton);

        headerPanel.add(closePanel, java.awt.BorderLayout.EAST);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        tabbedPane.setFont(new java.awt.Font("Arial", 1, 14));
        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        dashboardTab.setBackground(new java.awt.Color(204, 0, 0));
        dashboardTab.setLayout(new java.awt.BorderLayout(20, 20));

        statsPanel.setBackground(new java.awt.Color(204, 0, 0));
        statsPanel.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        totalSalesPanel.setBackground(new java.awt.Color(255, 204, 0));
        totalSalesPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        totalSalesPanel.setLayout(new java.awt.BorderLayout());

        totalSalesLabel.setFont(new java.awt.Font("Arial", 1, 14));
        totalSalesLabel.setForeground(new java.awt.Color(153, 0, 0));
        totalSalesLabel.setText("Today's Sales");
        totalSalesPanel.add(totalSalesLabel, java.awt.BorderLayout.NORTH);

        totalSalesValue.setFont(new java.awt.Font("Arial", 1, 32));
        totalSalesValue.setForeground(new java.awt.Color(153, 0, 0));
        totalSalesValue.setText("P0.00");
        totalSalesPanel.add(totalSalesValue, java.awt.BorderLayout.CENTER);

        statsPanel.add(totalSalesPanel);

        totalOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));
        totalOrdersPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        totalOrdersPanel.setLayout(new java.awt.BorderLayout());

        totalOrdersLabel.setFont(new java.awt.Font("Arial", 1, 14));
        totalOrdersLabel.setForeground(new java.awt.Color(153, 0, 0));
        totalOrdersLabel.setText("Today's Orders");
        totalOrdersPanel.add(totalOrdersLabel, java.awt.BorderLayout.NORTH);

        totalOrdersValue.setFont(new java.awt.Font("Arial", 1, 32));
        totalOrdersValue.setForeground(new java.awt.Color(204, 0, 0));
        totalOrdersValue.setText("0");
        totalOrdersPanel.add(totalOrdersValue, java.awt.BorderLayout.CENTER);

        statsPanel.add(totalOrdersPanel);

        menuItemsCountPanel.setBackground(new java.awt.Color(255, 238, 153));
        menuItemsCountPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        menuItemsCountPanel.setLayout(new java.awt.BorderLayout());

        menuItemsCountLabel.setFont(new java.awt.Font("Arial", 1, 14));
        menuItemsCountLabel.setForeground(new java.awt.Color(153, 0, 0));
        menuItemsCountLabel.setText("Menu Items");
        menuItemsCountPanel.add(menuItemsCountLabel, java.awt.BorderLayout.NORTH);

        menuItemsCountValue.setFont(new java.awt.Font("Arial", 1, 32));
        menuItemsCountValue.setForeground(new java.awt.Color(204, 0, 0));
        menuItemsCountValue.setText("0");
        menuItemsCountPanel.add(menuItemsCountValue, java.awt.BorderLayout.CENTER);

        statsPanel.add(menuItemsCountPanel);

        dashboardTab.add(statsPanel, java.awt.BorderLayout.NORTH);

        welcomeLabel.setFont(new java.awt.Font("Arial", 1, 24));
        welcomeLabel.setForeground(new java.awt.Color(255, 204, 0));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome to Jollibee Admin Dashboard!");
        welcomeLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 0, 0, 0));
        dashboardTab.add(welcomeLabel, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Dashboard", dashboardTab);

        menuTab.setBackground(new java.awt.Color(255, 255, 255));
        menuTab.setLayout(new java.awt.BorderLayout(10, 10));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Category", "Price (P)", "Description", "Image Path"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuTable.setFont(new java.awt.Font("Arial", 0, 12));
        menuTable.setRowHeight(28);
        menuTable.getTableHeader().setFont(new java.awt.Font("Arial", 1, 12));
        menuTable.getTableHeader().setBackground(JOLLIBEE_RED);
        menuTable.getTableHeader().setForeground(Color.WHITE);
        menuTable.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                menuTableSelectionChanged(evt);
            }
        });
        menuScrollPane.setViewportView(menuTable);

        menuTab.add(menuScrollPane, java.awt.BorderLayout.CENTER);

        menuButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        addMenuItemButton.setFont(new java.awt.Font("Arial", 1, 12));
        addMenuItemButton.setText("Add Item");
        addMenuItemButton.setBackground(new java.awt.Color(255, 204, 0));
        addMenuItemButton.setForeground(new java.awt.Color(153, 0, 0));
        addMenuItemButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        addMenuItemButton.setFocusPainted(false);
        addMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemButtonActionPerformed(evt);
            }
        });
        menuButtonPanel.add(addMenuItemButton);

        editMenuItemButton.setFont(new java.awt.Font("Arial", 1, 12));
        editMenuItemButton.setText("Edit Item");
        editMenuItemButton.setBackground(new java.awt.Color(255, 238, 153));
        editMenuItemButton.setForeground(new java.awt.Color(153, 0, 0));
        editMenuItemButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        editMenuItemButton.setFocusPainted(false);
        editMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuItemButtonActionPerformed(evt);
            }
        });
        menuButtonPanel.add(editMenuItemButton);

        deleteMenuItemButton.setFont(new java.awt.Font("Arial", 1, 12));
        deleteMenuItemButton.setText("Delete Item");
        deleteMenuItemButton.setBackground(new java.awt.Color(204, 0, 0));
        deleteMenuItemButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteMenuItemButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        deleteMenuItemButton.setFocusPainted(false);
        deleteMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemButtonActionPerformed(evt);
            }
        });
        menuButtonPanel.add(deleteMenuItemButton);

        refreshMenuButton.setFont(new java.awt.Font("Arial", 1, 12));
        refreshMenuButton.setText("Refresh");
        refreshMenuButton.setBackground(new java.awt.Color(128, 128, 128));
        refreshMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshMenuButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        refreshMenuButton.setFocusPainted(false);
        refreshMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMenuButtonActionPerformed(evt);
            }
        });
        menuButtonPanel.add(refreshMenuButton);

        menuTab.add(menuButtonPanel, java.awt.BorderLayout.SOUTH);

        tabbedPane.addTab("Menu Management", menuTab);

        historyTab.setBackground(new java.awt.Color(255, 255, 255));
        historyTab.setLayout(new java.awt.BorderLayout(10, 10));

        historyTopPanel.setBackground(new java.awt.Color(255, 238, 153));
        historyTopPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        searchLabel.setFont(new java.awt.Font("Arial", 1, 12));
        searchLabel.setForeground(new java.awt.Color(153, 0, 0));
        searchLabel.setText("Search:");
        historyTopPanel.add(searchLabel);

        searchField.setFont(new java.awt.Font("Arial", 0, 12));
        searchField.setPreferredSize(new java.awt.Dimension(250, 30));
        searchField.setBorder(BorderFactory.createLineBorder(JOLLIBEE_YELLOW, 2));
        historyTopPanel.add(searchField);

        searchButton.setFont(new java.awt.Font("Arial", 1, 12));
        searchButton.setText("Search");
        searchButton.setBackground(new java.awt.Color(255, 204, 0));
        searchButton.setForeground(new java.awt.Color(153, 0, 0));
        searchButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        searchButton.setFocusPainted(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        historyTopPanel.add(searchButton);

        showAllButton.setFont(new java.awt.Font("Arial", 1, 12));
        showAllButton.setText("Show All");
        showAllButton.setBackground(new java.awt.Color(128, 128, 128));
        showAllButton.setForeground(new java.awt.Color(255, 255, 255));
        showAllButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        showAllButton.setFocusPainted(false);
        showAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllButtonActionPerformed(evt);
            }
        });
        historyTopPanel.add(showAllButton);

        historyTab.add(historyTopPanel, java.awt.BorderLayout.NORTH);

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Buyer Name", "Items Ordered", "Total (P)", "Date", "Payment", "Status"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historyTable.setFont(new java.awt.Font("Arial", 0, 12));
        historyTable.setRowHeight(28);
        historyTable.getTableHeader().setFont(new java.awt.Font("Arial", 1, 12));
        historyTable.getTableHeader().setBackground(JOLLIBEE_RED);
        historyTable.getTableHeader().setForeground(Color.WHITE);
        historyScrollPane.setViewportView(historyTable);

        historyTab.add(historyScrollPane, java.awt.BorderLayout.CENTER);

        historyButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        historyButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));

        refreshHistoryButton.setFont(new java.awt.Font("Arial", 1, 12));
        refreshHistoryButton.setText("Refresh");
        refreshHistoryButton.setBackground(new java.awt.Color(128, 128, 128));
        refreshHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshHistoryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        refreshHistoryButton.setFocusPainted(false);
        refreshHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshHistoryButtonActionPerformed(evt);
            }
        });
        historyButtonPanel.add(refreshHistoryButton);

        exportButton.setFont(new java.awt.Font("Arial", 1, 12));
        exportButton.setText("Export Data");
        exportButton.setBackground(new java.awt.Color(255, 204, 0));
        exportButton.setForeground(new java.awt.Color(153, 0, 0));
        exportButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        exportButton.setFocusPainted(false);
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        historyButtonPanel.add(exportButton);

        historyTab.add(historyButtonPanel, java.awt.BorderLayout.SOUTH);

        tabbedPane.addTab("Buyer History", historyTab);

        mainPanel.add(tabbedPane, java.awt.BorderLayout.CENTER);

        add(mainPanel);

        pack();
        setLocationRelativeTo(getParent());
    }// </editor-fold>//GEN-END:initComponents

    private void loadLogo() {
        try {
            boolean logoLoaded = false;

            // Try 1: Load from classpath
            java.net.URL logoUrl = getClass().getResource("/images/jollibee_logo.png");
            if (logoUrl != null) {
                ImageIcon logoIcon = new ImageIcon(logoUrl);
                Image scaledLogo = logoIcon.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                logoLabel.setIcon(new ImageIcon(scaledLogo));
                logoLoaded = true;
            }

            // Try 2: NetBeans structure
            if (!logoLoaded) {
                File f = new File("src/restaurantpos/images/jollibee_logo.png");
                if (f.exists()) {
                    ImageIcon logoIcon = new ImageIcon(f.getAbsolutePath());
                    Image scaledLogo = logoIcon.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                    logoLabel.setIcon(new ImageIcon(scaledLogo));
                    logoLoaded = true;
                }
            }

            // Try 3: IntelliJ structure
            if (!logoLoaded) {
                File f = new File("RestaurantPOS/src/restaurantpos/images/jollibee_logo.png");
                if (f.exists()) {
                    ImageIcon logoIcon = new ImageIcon(f.getAbsolutePath());
                    Image scaledLogo = logoIcon.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                    logoLabel.setIcon(new ImageIcon(scaledLogo));
                    logoLoaded = true;
                }
            }

            // Try 4: images folder directly
            if (!logoLoaded) {
                File f = new File("images/jollibee_logo.png");
                if (f.exists()) {
                    ImageIcon logoIcon = new ImageIcon(f.getAbsolutePath());
                    Image scaledLogo = logoIcon.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                    logoLabel.setIcon(new ImageIcon(scaledLogo));
                    logoLoaded = true;
                }
            }

            // Fallback to admin_logo.png
            if (!logoLoaded) {
                File f = new File("src/restaurantpos/images/admin_logo.png");
                if (f.exists()) {
                    ImageIcon logoIcon = new ImageIcon(f.getAbsolutePath());
                    Image scaledLogo = logoIcon.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                    logoLabel.setIcon(new ImageIcon(scaledLogo));
                }
            }
        } catch (Exception e) {
            // If no image, just skip
        }
    }

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void menuTableSelectionChanged(javax.swing.event.ListSelectionEvent evt) {
        int selectedRow = menuTable.getSelectedRow();
        if (selectedRow >= 0) {
            int id = (int) menuTable.getValueAt(selectedRow, 0);
            for (MenuItem item : menuItems) {
                if (item.getId() == id) {
                    selectedMenuItem = item;
                    break;
                }
            }
        }
    }

    private void addMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemButtonActionPerformed
        MenuItemDialog dialog = new MenuItemDialog((java.awt.Frame) null, true, null);
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            loadMenuItems();
            updateDashboard();
        }
    }//GEN-LAST:event_addMenuItemButtonActionPerformed

    private void editMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuItemButtonActionPerformed
        if (selectedMenuItem == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a menu item to edit!",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        MenuItemDialog dialog = new MenuItemDialog((java.awt.Frame) null, true, selectedMenuItem);
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            loadMenuItems();
        }
    }//GEN-LAST:event_editMenuItemButtonActionPerformed

    private void deleteMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemButtonActionPerformed
        if (selectedMenuItem == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a menu item to delete!",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete '" + selectedMenuItem.getName() + "'?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            if (dbHandler.deleteMenuItem(selectedMenuItem.getId())) {
                JOptionPane.showMessageDialog(this,
                        "Menu item deleted successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                selectedMenuItem = null;
                loadMenuItems();
                updateDashboard();
            }
        }
    }//GEN-LAST:event_deleteMenuItemButtonActionPerformed

    private void refreshMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMenuButtonActionPerformed
        loadMenuItems();
    }//GEN-LAST:event_refreshMenuButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String searchTerm = searchField.getText().trim();
        if (searchTerm.isEmpty()) {
            loadBuyerHistory();
            return;
        }
        buyerHistory = dbHandler.searchBuyerHistory(searchTerm);
        updateHistoryTable();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void showAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllButtonActionPerformed
        searchField.setText("");
        loadBuyerHistory();
    }//GEN-LAST:event_showAllButtonActionPerformed

    private void refreshHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshHistoryButtonActionPerformed
        loadBuyerHistory();
    }//GEN-LAST:event_refreshHistoryButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Export Buyer History");
        fileChooser.setSelectedFile(new File("jollibee_buyer_history.csv"));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                PrintWriter writer = new PrintWriter(fileChooser.getSelectedFile());
                writer.println("ID,Buyer Name,Items Ordered,Total Amount,Order Date,Payment Method,Status");
                for (BuyerHistory record : buyerHistory) {
                    writer.println(String.format("%d,\"%s\",\"%s\",%.2f,\"%s\",\"%s\",\"%s\"",
                            record.getId(),
                            record.getBuyerName(),
                            record.getItemsOrdered().replace("\"", "\"\""),
                            record.getTotalAmount(),
                            record.getOrderDate(),
                            record.getPaymentMethod(),
                            record.getStatus()
                    ));
                }
                writer.close();
                JOptionPane.showMessageDialog(this,
                        "Data exported successfully!",
                        "Export Complete",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error exporting data: " + e.getMessage(),
                        "Export Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel closePanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JPanel totalSalesPanel;
    private javax.swing.JLabel totalSalesLabel;
    private javax.swing.JLabel totalSalesValue;
    private javax.swing.JPanel totalOrdersPanel;
    private javax.swing.JLabel totalOrdersLabel;
    private javax.swing.JLabel totalOrdersValue;
    private javax.swing.JPanel menuItemsCountPanel;
    private javax.swing.JLabel menuItemsCountLabel;
    private javax.swing.JLabel menuItemsCountValue;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel menuTab;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JTable menuTable;
    private javax.swing.JPanel menuButtonPanel;
    private javax.swing.JButton addMenuItemButton;
    private javax.swing.JButton editMenuItemButton;
    private javax.swing.JButton deleteMenuItemButton;
    private javax.swing.JButton refreshMenuButton;
    private javax.swing.JPanel historyTab;
    private javax.swing.JPanel historyTopPanel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showAllButton;
    private javax.swing.JScrollPane historyScrollPane;
    private javax.swing.JTable historyTable;
    private javax.swing.JPanel historyButtonPanel;
    private javax.swing.JButton refreshHistoryButton;
    private javax.swing.JButton exportButton;
    // End of variables declaration//GEN-END:variables

    private void loadMenuItems() {
        menuItems = dbHandler.getAllMenuItems();
        updateMenuTable();
    }

    private void updateMenuTable() {
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        for (MenuItem item : menuItems) {
            model.addRow(new Object[] {
                    item.getId(),
                    item.getName(),
                    item.getCategory(),
                    String.format("%.2f", item.getPrice()),
                    item.getDescription(),
                    item.getImagePath() != null ? item.getImagePath() : ""
            });
        }
    }

    private void loadBuyerHistory() {
        buyerHistory = dbHandler.getAllBuyerHistory();
        updateHistoryTable();
    }

    private void updateHistoryTable() {
        DefaultTableModel model = (DefaultTableModel) historyTable.getModel();
        model.setRowCount(0);
        for (BuyerHistory record : buyerHistory) {
            model.addRow(new Object[] {
                    record.getId(),
                    record.getBuyerName(),
                    record.getItemsOrdered(),
                    String.format("%.2f", record.getTotalAmount()),
                    record.getOrderDate(),
                    record.getPaymentMethod(),
                    record.getStatus()
            });
        }
    }

    private void updateDashboard() {
        double todaySales = dbHandler.getTotalSalesToday();
        totalSalesValue.setText(String.format("P%.2f", todaySales));

        int todayOrders = dbHandler.getTotalOrdersToday();
        totalOrdersValue.setText(String.valueOf(todayOrders));

        menuItemsCountValue.setText(String.valueOf(menuItems.size()));
    }
}