package restaurantpos;

import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.border.*;

/**
 * MainFrame - Jollibee Menu System Main Window
 *
 * @author JollibeePOS
 */
public class MainFrame extends javax.swing.JFrame {

    // Jollibee Brand Colors
    private static final Color JOLLIBEE_RED = new Color(204, 0, 0);
    private static final Color JOLLIBEE_YELLOW = new Color(255, 204, 0);
    private static final Color JOLLIBEE_DARK_RED = new Color(153, 0, 0);
    private static final Color JOLLIBEE_LIGHT_YELLOW = new Color(255, 238, 153);

    private DatabaseHandler dbHandler;
    private List<MenuItem> menuItems;
    private Map<Integer, Integer> cart; // MenuItem ID -> Quantity
    private String currentCategory = "All";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        dbHandler = DatabaseHandler.getInstance();
        cart = new HashMap<>();
        initComponents();
        loadLogo();
        loadMenuItems();
        updateStatusBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        taglineLabel = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        adminButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        categoryPanel = new javax.swing.JPanel();
        categoryAllButton = new javax.swing.JButton();
        categoryBurgersButton = new javax.swing.JButton();
        categoryChickenButton = new javax.swing.JButton();
        categoryPastaButton = new javax.swing.JButton();
        categoryRiceMealsButton = new javax.swing.JButton();
        categoryDrinksButton = new javax.swing.JButton();
        categoryDessertsButton = new javax.swing.JButton();
        menuScrollPane = new javax.swing.JScrollPane();
        menuItemsPanel = new javax.swing.JPanel();
        placeholder1 = new javax.swing.JPanel();
        placeholderImg1 = new javax.swing.JLabel();
        placeholderInfo1 = new javax.swing.JPanel();
        placeholderName1 = new javax.swing.JLabel();
        placeholderPrice1 = new javax.swing.JLabel();
        placeholderBtn1 = new javax.swing.JButton();
        placeholder2 = new javax.swing.JPanel();
        placeholderImg2 = new javax.swing.JLabel();
        placeholderInfo2 = new javax.swing.JPanel();
        placeholderName2 = new javax.swing.JLabel();
        placeholderPrice2 = new javax.swing.JLabel();
        placeholderBtn2 = new javax.swing.JButton();
        placeholder3 = new javax.swing.JPanel();
        placeholderImg3 = new javax.swing.JLabel();
        placeholderInfo3 = new javax.swing.JPanel();
        placeholderName3 = new javax.swing.JLabel();
        placeholderPrice3 = new javax.swing.JLabel();
        placeholderBtn3 = new javax.swing.JButton();
        cartPanel = new javax.swing.JPanel();
        cartHeaderPanel = new javax.swing.JPanel();
        cartTitleLabel = new javax.swing.JLabel();
        cartScrollPane = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        cartBottomPanel = new javax.swing.JPanel();
        totalPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        totalValueLabel = new javax.swing.JLabel();
        buyerInfoPanel = new javax.swing.JPanel();
        buyerNameLabel = new javax.swing.JLabel();
        buyerNameField = new javax.swing.JTextField();
        paymentMethodLabel = new javax.swing.JLabel();
        paymentMethodCombo = new javax.swing.JComboBox<>();
        buttonsPanel = new javax.swing.JPanel();
        clearCartButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        statusBar = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jollibee Menu System");
        setMinimumSize(new java.awt.Dimension(1200, 700));

        mainPanel.setBackground(new java.awt.Color(204, 0, 0));
        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(204, 0, 0));
        headerPanel.setPreferredSize(new java.awt.Dimension(1180, 80));
        headerPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setBackground(new java.awt.Color(204, 0, 0));
        titlePanel.setLayout(new javax.swing.BoxLayout(titlePanel, javax.swing.BoxLayout.Y_AXIS));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 28));
        titleLabel.setForeground(new java.awt.Color(255, 204, 0));
        titleLabel.setText("JOLLIBEE MENU SYSTEM");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 5, 10));
        titlePanel.add(titleLabel);

        taglineLabel.setFont(new java.awt.Font("Arial", 2, 12));
        taglineLabel.setForeground(new java.awt.Color(255, 255, 255));
        taglineLabel.setText("Langhap-Sarap! Philippines' #1 Fast Food Chain");
        taglineLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 10, 10));
        titlePanel.add(taglineLabel);

        headerPanel.add(titlePanel, java.awt.BorderLayout.WEST);

        adminPanel.setBackground(new java.awt.Color(204, 0, 0));
        adminPanel.setPreferredSize(new java.awt.Dimension(150, 80));
        adminPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 25));

        adminButton.setFont(new java.awt.Font("Arial", 1, 14));
        adminButton.setText("Admin Panel");
        adminButton.setBackground(new java.awt.Color(255, 204, 0));
        adminButton.setForeground(new java.awt.Color(153, 0, 0));
        adminButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 25, 10, 25));
        adminButton.setFocusPainted(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        adminPanel.add(adminButton);

        headerPanel.add(adminPanel, java.awt.BorderLayout.EAST);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setBackground(new java.awt.Color(204, 0, 0));
        centerPanel.setLayout(new java.awt.BorderLayout(10, 0));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setLayout(new java.awt.BorderLayout());

        categoryPanel.setBackground(new java.awt.Color(255, 238, 153));
        categoryPanel.setPreferredSize(new java.awt.Dimension(700, 50));
        categoryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        categoryAllButton.setFont(new java.awt.Font("Arial", 1, 12));
        categoryAllButton.setText("All");
        categoryAllButton.setBackground(new java.awt.Color(204, 0, 0));
        categoryAllButton.setForeground(new java.awt.Color(255, 255, 255));
        categoryAllButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 20, 8, 20));
        categoryAllButton.setFocusPainted(false);
        categoryAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryAllButtonActionPerformed(evt);
            }
        });
        categoryPanel.add(categoryAllButton);

        categoryBurgersButton.setFont(new java.awt.Font("Arial", 1, 12));
        categoryBurgersButton.setText("Burgers");
        categoryBurgersButton.setBackground(new java.awt.Color(255, 238, 153));
        categoryBurgersButton.setForeground(new java.awt.Color(153, 0, 0));
        categoryBurgersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        categoryBurgersButton.setFocusPainted(false);
        categoryBurgersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBurgersButtonActionPerformed(evt);
            }
        });
        categoryPanel.add(categoryBurgersButton);

        categoryChickenButton.setFont(new java.awt.Font("Arial", 1, 12));
        categoryChickenButton.setText("Chicken");
        categoryChickenButton.setBackground(new java.awt.Color(255, 238, 153));
        categoryChickenButton.setForeground(new java.awt.Color(153, 0, 0));
        categoryChickenButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        categoryChickenButton.setFocusPainted(false);
        categoryChickenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryChickenButtonActionPerformed(evt);
            }
        });
        categoryPanel.add(categoryChickenButton);

        categoryPastaButton.setFont(new java.awt.Font("Arial", 1, 12));
        categoryPastaButton.setText("Pasta");
        categoryPastaButton.setBackground(new java.awt.Color(255, 238, 153));
        categoryPastaButton.setForeground(new java.awt.Color(153, 0, 0));
        categoryPastaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        categoryPastaButton.setFocusPainted(false);
        categoryPastaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryPastaButtonActionPerformed(evt);
            }
        });
        categoryPanel.add(categoryPastaButton);

        categoryRiceMealsButton.setFont(new java.awt.Font("Arial", 1, 12));
        categoryRiceMealsButton.setText("Rice Meals");
        categoryRiceMealsButton.setBackground(new java.awt.Color(255, 238, 153));
        categoryRiceMealsButton.setForeground(new java.awt.Color(153, 0, 0));
        categoryRiceMealsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        categoryRiceMealsButton.setFocusPainted(false);
        categoryRiceMealsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryRiceMealsButtonActionPerformed(evt);
            }
        });
        categoryPanel.add(categoryRiceMealsButton);

        categoryDrinksButton.setFont(new java.awt.Font("Arial", 1, 12));
        categoryDrinksButton.setText("Drinks");
        categoryDrinksButton.setBackground(new java.awt.Color(255, 238, 153));
        categoryDrinksButton.setForeground(new java.awt.Color(153, 0, 0));
        categoryDrinksButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        categoryDrinksButton.setFocusPainted(false);
        categoryDrinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryDrinksButtonActionPerformed(evt);
            }
        });
        categoryPanel.add(categoryDrinksButton);

        categoryDessertsButton.setFont(new java.awt.Font("Arial", 1, 12));
        categoryDessertsButton.setText("Desserts");
        categoryDessertsButton.setBackground(new java.awt.Color(255, 238, 153));
        categoryDessertsButton.setForeground(new java.awt.Color(153, 0, 0));
        categoryDessertsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        categoryDessertsButton.setFocusPainted(false);
        categoryDessertsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryDessertsButtonActionPerformed(evt);
            }
        });
        categoryPanel.add(categoryDessertsButton);

        menuPanel.add(categoryPanel, java.awt.BorderLayout.NORTH);

        menuScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createTitledBorder(""),
                "MENU ITEMS (Loaded from Database)",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Arial", 1, 14),
                new java.awt.Color(153, 0, 0)));

        menuItemsPanel.setBackground(new java.awt.Color(255, 250, 240));
        menuItemsPanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        // Placeholder panels for design view
        createPlaceholderPanel(placeholder1, placeholderImg1, placeholderInfo1, placeholderName1, placeholderPrice1, placeholderBtn1);
        createPlaceholderPanel(placeholder2, placeholderImg2, placeholderInfo2, placeholderName2, placeholderPrice2, placeholderBtn2);
        createPlaceholderPanel(placeholder3, placeholderImg3, placeholderInfo3, placeholderName3, placeholderPrice3, placeholderBtn3);

        menuItemsPanel.add(placeholder1);
        menuItemsPanel.add(placeholder2);
        menuItemsPanel.add(placeholder3);

        menuScrollPane.setViewportView(menuItemsPanel);

        menuPanel.add(menuScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(menuPanel, java.awt.BorderLayout.CENTER);

        cartPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartPanel.setPreferredSize(new java.awt.Dimension(380, 500));
        cartPanel.setLayout(new java.awt.BorderLayout());

        cartHeaderPanel.setBackground(new java.awt.Color(255, 204, 0));
        cartHeaderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        cartTitleLabel.setFont(new java.awt.Font("Arial", 1, 16));
        cartTitleLabel.setForeground(new java.awt.Color(153, 0, 0));
        cartTitleLabel.setText("YOUR ORDER");
        cartHeaderPanel.add(cartTitleLabel);

        cartPanel.add(cartHeaderPanel, java.awt.BorderLayout.NORTH);

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {"Item", "Qty", "Price", "Subtotal"}
        ) {
            boolean[] canEdit = new boolean [] {false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setRowHeight(25);
        cartScrollPane.setViewportView(cartTable);

        cartPanel.add(cartScrollPane, java.awt.BorderLayout.CENTER);

        cartBottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartBottomPanel.setLayout(new javax.swing.BoxLayout(cartBottomPanel, javax.swing.BoxLayout.Y_AXIS));

        totalPanel.setBackground(new java.awt.Color(255, 238, 153));
        totalPanel.setPreferredSize(new java.awt.Dimension(380, 50));
        totalPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        totalLabel.setFont(new java.awt.Font("Arial", 1, 18));
        totalLabel.setForeground(new java.awt.Color(153, 0, 0));
        totalLabel.setText("TOTAL:");
        totalPanel.add(totalLabel);

        totalValueLabel.setFont(new java.awt.Font("Arial", 1, 24));
        totalValueLabel.setForeground(new java.awt.Color(204, 0, 0));
        totalValueLabel.setText("P0.00");
        totalPanel.add(totalValueLabel);

        cartBottomPanel.add(totalPanel);

        buyerInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        buyerInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createTitledBorder(""),
                "Buyer Information",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Arial", 1, 12),
                new java.awt.Color(153, 0, 0)));
        buyerInfoPanel.setLayout(new java.awt.GridLayout(2, 2));

        buyerNameLabel.setFont(new java.awt.Font("Arial", 1, 12));
        buyerNameLabel.setText("Buyer Name:");
        buyerInfoPanel.add(buyerNameLabel);
        buyerInfoPanel.add(buyerNameField);

        paymentMethodLabel.setFont(new java.awt.Font("Arial", 1, 12));
        paymentMethodLabel.setText("Payment Method:");
        buyerInfoPanel.add(paymentMethodLabel);

        paymentMethodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Cash", "GCash", "Maya", "Credit Card", "Debit Card"}));
        buyerInfoPanel.add(paymentMethodCombo);

        cartBottomPanel.add(buyerInfoPanel);

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(380, 60));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        clearCartButton.setFont(new java.awt.Font("Arial", 1, 14));
        clearCartButton.setText("Clear Cart");
        clearCartButton.setBackground(new java.awt.Color(102, 102, 102));
        clearCartButton.setForeground(new java.awt.Color(255, 255, 255));
        clearCartButton.setFocusPainted(false);
        clearCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCartButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(clearCartButton);

        checkoutButton.setFont(new java.awt.Font("Arial", 1, 14));
        checkoutButton.setText("Checkout");
        checkoutButton.setBackground(new java.awt.Color(255, 204, 0));
        checkoutButton.setForeground(new java.awt.Color(153, 0, 0));
        checkoutButton.setFocusPainted(false);
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(checkoutButton);

        cartBottomPanel.add(buttonsPanel);

        cartPanel.add(cartBottomPanel, java.awt.BorderLayout.SOUTH);

        centerPanel.add(cartPanel, java.awt.BorderLayout.EAST);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        statusBar.setBackground(new java.awt.Color(153, 0, 0));
        statusBar.setPreferredSize(new java.awt.Dimension(1180, 30));
        statusBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        statusLabel.setFont(new java.awt.Font("Arial", 0, 12));
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText("Ready | Today's Orders: 0 | Today's Sales: P0.00");
        statusBar.add(statusLabel);

        mainPanel.add(statusBar, java.awt.BorderLayout.SOUTH);

        add(mainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadLogo() {
        try {
            // Create logo label
            JLabel logoLabel = new JLabel();
            logoLabel.setPreferredSize(new java.awt.Dimension(80, 80));

            // Try loading jollibee_logo.png from classpath
            java.net.URL logoUrl = getClass().getResource("/images/jollibee_logo.png");
            if (logoUrl != null) {
                ImageIcon logoIcon = new ImageIcon(logoUrl);
                Image scaledLogo = logoIcon.getImage().getScaledInstance(75, 75, Image.SCALE_SMOOTH);
                logoLabel.setIcon(new ImageIcon(scaledLogo));
            } else {
                // Try loading from file system
                File f = new File("src/restaurantpos/images/jollibee_logo.png");
                if (f.exists()) {
                    ImageIcon logoIcon = new ImageIcon(f.getAbsolutePath());
                    Image scaledLogo = logoIcon.getImage().getScaledInstance(75, 75, Image.SCALE_SMOOTH);
                    logoLabel.setIcon(new ImageIcon(scaledLogo));
                }
            }

            // Create a new panel to hold logo and titlePanel side by side
            JPanel newWestPanel = new JPanel(new BorderLayout());
            newWestPanel.setBackground(new java.awt.Color(204, 0, 0));

            // Add logo on the left
            JPanel logoPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 5));
            logoPanel.setBackground(new java.awt.Color(204, 0, 0));
            logoPanel.add(logoLabel);
            newWestPanel.add(logoPanel, BorderLayout.WEST);

            // Add titlePanel next to it
            newWestPanel.add(titlePanel, BorderLayout.CENTER);

            // Replace the header's WEST component
            headerPanel.remove(titlePanel);
            headerPanel.add(newWestPanel, BorderLayout.WEST);
            headerPanel.revalidate();
            headerPanel.repaint();

        } catch (Exception e) {
            // If logo fails to load, just continue without it
            System.out.println("Could not load logo: " + e.getMessage());
        }
    }

    private void createPlaceholderPanel(JPanel panel, JLabel imgLabel, JPanel infoPanel, JLabel nameLabel, JLabel priceLabel, JButton btn) {
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createLineBorder(JOLLIBEE_LIGHT_YELLOW, 2, true));
        panel.setPreferredSize(new Dimension(200, 180));
        panel.setLayout(new BorderLayout());

        imgLabel.setBackground(JOLLIBEE_LIGHT_YELLOW);
        imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
        imgLabel.setText("[Menu Item Image]");
        imgLabel.setOpaque(true);
        imgLabel.setPreferredSize(new Dimension(200, 100));
        panel.add(imgLabel, BorderLayout.NORTH);

        infoPanel.setBackground(Color.WHITE);
        infoPanel.setLayout(new GridLayout(3, 1));

        nameLabel.setFont(new Font("Arial", Font.BOLD, 12));
        nameLabel.setHorizontalAlignment(SwingConstants.CENTER);
        nameLabel.setText("Menu Item Name");
        infoPanel.add(nameLabel);

        priceLabel.setFont(new Font("Arial", Font.BOLD, 14));
        priceLabel.setForeground(JOLLIBEE_RED);
        priceLabel.setHorizontalAlignment(SwingConstants.CENTER);
        priceLabel.setText("P0.00");
        infoPanel.add(priceLabel);

        btn.setText("Add to Cart");
        btn.setFont(new Font("Arial", Font.BOLD, 10));
        btn.setBackground(JOLLIBEE_YELLOW);
        btn.setForeground(JOLLIBEE_DARK_RED);
        btn.setFocusPainted(false);
        infoPanel.add(btn);

        panel.add(infoPanel, BorderLayout.CENTER);
    }

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        AdminLoginDialog loginDialog = new AdminLoginDialog(this, true);
        loginDialog.setVisible(true);

        // Check if login was successful before opening dashboard
        if (loginDialog.isAuthenticated()) {
            AdminDashboard dashboard = new AdminDashboard(this, true);
            dashboard.setVisible(true);
        }
    }//GEN-LAST:event_adminButtonActionPerformed

    private void categoryAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryAllButtonActionPerformed
        currentCategory = "All";
        updateCategoryButtons();
        loadMenuItems();
    }//GEN-LAST:event_categoryAllButtonActionPerformed

    private void categoryBurgersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryBurgersButtonActionPerformed
        currentCategory = "Burgers";
        updateCategoryButtons();
        loadMenuItems();
    }//GEN-LAST:event_categoryBurgersButtonActionPerformed

    private void categoryChickenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryChickenButtonActionPerformed
        currentCategory = "Chicken";
        updateCategoryButtons();
        loadMenuItems();
    }//GEN-LAST:event_categoryChickenButtonActionPerformed

    private void categoryPastaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryPastaButtonActionPerformed
        currentCategory = "Pasta";
        updateCategoryButtons();
        loadMenuItems();
    }//GEN-LAST:event_categoryPastaButtonActionPerformed

    private void categoryRiceMealsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryRiceMealsButtonActionPerformed
        currentCategory = "Rice Meals";
        updateCategoryButtons();
        loadMenuItems();
    }//GEN-LAST:event_categoryRiceMealsButtonActionPerformed

    private void categoryDrinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryDrinksButtonActionPerformed
        currentCategory = "Drinks";
        updateCategoryButtons();
        loadMenuItems();
    }//GEN-LAST:event_categoryDrinksButtonActionPerformed

    private void categoryDessertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryDessertsButtonActionPerformed
        currentCategory = "Desserts";
        updateCategoryButtons();
        loadMenuItems();
    }//GEN-LAST:event_categoryDessertsButtonActionPerformed

    private void clearCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCartButtonActionPerformed
        cart.clear();
        updateCartTable();
    }//GEN-LAST:event_clearCartButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        if (cart.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Your cart is empty!", "Empty Cart", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String buyerName = buyerNameField.getText().trim();
        if (buyerName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter buyer name!", "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String paymentMethod = (String) paymentMethodCombo.getSelectedItem();
        double total = calculateTotal();

        // Save to database
        StringBuilder itemsBuilder = new StringBuilder();
        for (Map.Entry<Integer, Integer> entry : cart.entrySet()) {
            MenuItem item = getMenuItemById(entry.getKey());
            if (item != null) {
                if (itemsBuilder.length() > 0) itemsBuilder.append(", ");
                itemsBuilder.append(item.getName()).append(" x").append(entry.getValue());
            }
        }

        String orderDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        BuyerHistory history = new BuyerHistory(0, buyerName, itemsBuilder.toString(), total, orderDate, paymentMethod, "Completed");

        if (dbHandler.addBuyerHistory(history)) {
            JOptionPane.showMessageDialog(this,
                    String.format("Order placed successfully!\nTotal: P%.2f\nPayment: %s", total, paymentMethod),
                    "Order Complete", JOptionPane.INFORMATION_MESSAGE);
            cart.clear();
            buyerNameField.setText("");
            updateCartTable();
            updateStatusBar();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save order!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_checkoutButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel taglineLabel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton adminButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JButton categoryAllButton;
    private javax.swing.JButton categoryBurgersButton;
    private javax.swing.JButton categoryChickenButton;
    private javax.swing.JButton categoryPastaButton;
    private javax.swing.JButton categoryRiceMealsButton;
    private javax.swing.JButton categoryDrinksButton;
    private javax.swing.JButton categoryDessertsButton;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JPanel menuItemsPanel;
    private javax.swing.JPanel placeholder1;
    private javax.swing.JLabel placeholderImg1;
    private javax.swing.JPanel placeholderInfo1;
    private javax.swing.JLabel placeholderName1;
    private javax.swing.JLabel placeholderPrice1;
    private javax.swing.JButton placeholderBtn1;
    private javax.swing.JPanel placeholder2;
    private javax.swing.JLabel placeholderImg2;
    private javax.swing.JPanel placeholderInfo2;
    private javax.swing.JLabel placeholderName2;
    private javax.swing.JLabel placeholderPrice2;
    private javax.swing.JButton placeholderBtn2;
    private javax.swing.JPanel placeholder3;
    private javax.swing.JLabel placeholderImg3;
    private javax.swing.JPanel placeholderInfo3;
    private javax.swing.JLabel placeholderName3;
    private javax.swing.JLabel placeholderPrice3;
    private javax.swing.JButton placeholderBtn3;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JPanel cartHeaderPanel;
    private javax.swing.JLabel cartTitleLabel;
    private javax.swing.JScrollPane cartScrollPane;
    private javax.swing.JTable cartTable;
    private javax.swing.JPanel cartBottomPanel;
    private javax.swing.JPanel totalPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalValueLabel;
    private javax.swing.JPanel buyerInfoPanel;
    private javax.swing.JLabel buyerNameLabel;
    private javax.swing.JTextField buyerNameField;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JComboBox<String> paymentMethodCombo;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton clearCartButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JPanel statusBar;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    private void loadMenuItems() {
        if (currentCategory.equals("All")) {
            menuItems = dbHandler.getAllMenuItems();
        } else {
            menuItems = dbHandler.getMenuItemsByCategory(currentCategory);
        }
        System.out.println("Loading menu items for category: " + currentCategory + ", found: " + (menuItems != null ? menuItems.size() : 0) + " items");
        displayMenuItems();
    }

    private void displayMenuItems() {
        // Remove all existing panels including placeholders
        menuItemsPanel.removeAll();

        // Reset layout
        menuItemsPanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        if (menuItems == null || menuItems.isEmpty()) {
            // Show a message if no items found
            JLabel noItemsLabel = new JLabel("No menu items found. Check database connection.", SwingConstants.CENTER);
            noItemsLabel.setFont(new Font("Arial", Font.BOLD, 16));
            noItemsLabel.setForeground(JOLLIBEE_DARK_RED);
            menuItemsPanel.setLayout(new java.awt.BorderLayout());
            menuItemsPanel.add(noItemsLabel, java.awt.BorderLayout.CENTER);
            menuItemsPanel.setPreferredSize(new Dimension(680, 100));
        } else {
            for (MenuItem item : menuItems) {
                JPanel itemPanel = createMenuItemPanel(item);
                menuItemsPanel.add(itemPanel);
            }

            // Calculate proper height based on number of items (3 per row)
            int rows = (int) Math.ceil(menuItems.size() / 3.0);
            int itemHeight = 190; // each item is 180px + 10px gap
            int totalHeight = rows * itemHeight + 20;

            // Set the preferred size so scrollpane works correctly
            menuItemsPanel.setPreferredSize(new Dimension(680, totalHeight));
            System.out.println("Displayed " + menuItems.size() + " items in " + rows + " rows, height=" + totalHeight);
        }

        // Force layout update
        menuItemsPanel.revalidate();
        menuItemsPanel.repaint();
        menuScrollPane.revalidate();
        menuScrollPane.repaint();
    }

    private JPanel createMenuItemPanel(final MenuItem item) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createLineBorder(JOLLIBEE_LIGHT_YELLOW, 2, true));
        panel.setPreferredSize(new Dimension(200, 180));

        // Image label
        JLabel imgLabel = new JLabel();
        imgLabel.setBackground(JOLLIBEE_LIGHT_YELLOW);
        imgLabel.setHorizontalAlignment(SwingConstants.CENTER);
        imgLabel.setOpaque(true);
        imgLabel.setPreferredSize(new Dimension(200, 100));

        // Try to load image from multiple locations
        boolean imageLoaded = false;
        if (item.getImagePath() != null && !item.getImagePath().isEmpty()) {
            String imagePath = item.getImagePath();
            System.out.println("Loading image for " + item.getName() + ": " + imagePath);

            // Try 1: Load from classpath resources (works in JAR and IDE)
            try {
                java.net.URL imgUrl = getClass().getResource("/" + imagePath);
                if (imgUrl != null) {
                    ImageIcon icon = new ImageIcon(imgUrl);
                    Image scaled = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                    imgLabel.setIcon(new ImageIcon(scaled));
                    imageLoaded = true;
                    System.out.println("  -> Loaded from classpath: " + imgUrl);
                }
            } catch (Exception e) {}

            // Try 2: Load from src folder (NetBeans project structure)
            if (!imageLoaded) {
                try {
                    File f = new File("src/restaurantpos/" + imagePath);
                    System.out.println("  -> Trying: " + f.getAbsolutePath() + " (exists: " + f.exists() + ")");
                    if (f.exists()) {
                        ImageIcon icon = new ImageIcon(f.getAbsolutePath());
                        Image scaled = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                        imgLabel.setIcon(new ImageIcon(scaled));
                        imageLoaded = true;
                        System.out.println("  -> Loaded from src folder");
                    }
                } catch (Exception e) {}
            }

            // Try 3: Load from project root (RestaurantPOS/src/...)
            if (!imageLoaded) {
                try {
                    File f = new File("RestaurantPOS/src/restaurantpos/" + imagePath);
                    System.out.println("  -> Trying: " + f.getAbsolutePath() + " (exists: " + f.exists() + ")");
                    if (f.exists()) {
                        ImageIcon icon = new ImageIcon(f.getAbsolutePath());
                        Image scaled = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                        imgLabel.setIcon(new ImageIcon(scaled));
                        imageLoaded = true;
                        System.out.println("  -> Loaded from project root");
                    }
                } catch (Exception e) {}
            }

            // Try 4: Load from absolute path (user's custom path)
            if (!imageLoaded) {
                try {
                    File f = new File(imagePath);
                    System.out.println("  -> Trying absolute: " + f.getAbsolutePath() + " (exists: " + f.exists() + ")");
                    if (f.exists()) {
                        ImageIcon icon = new ImageIcon(imagePath);
                        Image scaled = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                        imgLabel.setIcon(new ImageIcon(scaled));
                        imageLoaded = true;
                        System.out.println("  -> Loaded from absolute path");
                    }
                } catch (Exception e) {}
            }

            if (!imageLoaded) {
                System.out.println("  -> FAILED to load image for: " + item.getName());
            }
        }

        if (!imageLoaded) {
            imgLabel.setText("[Image]");
        }
        panel.add(imgLabel, BorderLayout.NORTH);

        // Info panel
        JPanel infoPanel = new JPanel(new GridLayout(3, 1));
        infoPanel.setBackground(Color.WHITE);

        JLabel nameLabel = new JLabel(item.getName(), SwingConstants.CENTER);
        nameLabel.setFont(new Font("Arial", Font.BOLD, 12));
        infoPanel.add(nameLabel);

        JLabel priceLabel = new JLabel(String.format("P%.2f", item.getPrice()), SwingConstants.CENTER);
        priceLabel.setFont(new Font("Arial", Font.BOLD, 14));
        priceLabel.setForeground(JOLLIBEE_RED);
        infoPanel.add(priceLabel);

        JButton addButton = new JButton("Add to Cart");
        addButton.setFont(new Font("Arial", Font.BOLD, 10));
        addButton.setBackground(JOLLIBEE_YELLOW);
        addButton.setForeground(JOLLIBEE_DARK_RED);
        addButton.setFocusPainted(false);
        addButton.addActionListener(e -> addToCart(item.getId()));
        infoPanel.add(addButton);

        panel.add(infoPanel, BorderLayout.CENTER);
        return panel;
    }

    private void addToCart(int itemId) {
        cart.put(itemId, cart.getOrDefault(itemId, 0) + 1);
        updateCartTable();
    }

    private void updateCartTable() {
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        model.setRowCount(0);

        double total = 0;
        for (Map.Entry<Integer, Integer> entry : cart.entrySet()) {
            MenuItem item = getMenuItemById(entry.getKey());
            if (item != null) {
                double subtotal = item.getPrice() * entry.getValue();
                model.addRow(new Object[] {
                        item.getName(),
                        entry.getValue(),
                        String.format("P%.2f", item.getPrice()),
                        String.format("P%.2f", subtotal)
                });
                total += subtotal;
            }
        }

        totalValueLabel.setText(String.format("P%.2f", total));
    }

    private double calculateTotal() {
        double total = 0;
        for (Map.Entry<Integer, Integer> entry : cart.entrySet()) {
            MenuItem item = getMenuItemById(entry.getKey());
            if (item != null) {
                total += item.getPrice() * entry.getValue();
            }
        }
        return total;
    }

    private MenuItem getMenuItemById(int id) {
        for (MenuItem item : dbHandler.getAllMenuItems()) {
            if (item.getId() == id) return item;
        }
        return null;
    }

    private void updateCategoryButtons() {
        JButton[] buttons = {categoryAllButton, categoryBurgersButton, categoryChickenButton,
                categoryPastaButton, categoryRiceMealsButton, categoryDrinksButton, categoryDessertsButton};
        String[] categories = {"All", "Burgers", "Chicken", "Pasta", "Rice Meals", "Drinks", "Desserts"};

        for (int i = 0; i < buttons.length; i++) {
            if (categories[i].equals(currentCategory)) {
                buttons[i].setBackground(JOLLIBEE_RED);
                buttons[i].setForeground(Color.WHITE);
            } else {
                buttons[i].setBackground(JOLLIBEE_LIGHT_YELLOW);
                buttons[i].setForeground(JOLLIBEE_DARK_RED);
            }
        }
    }

    private void updateStatusBar() {
        int todayOrders = dbHandler.getTotalOrdersToday();
        double todaySales = dbHandler.getTotalSalesToday();
        statusLabel.setText(String.format("Ready | Today's Orders: %d | Today's Sales: P%.2f", todayOrders, todaySales));
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }
}